[project]
dependencies = [
"accelerate==1.13.0", 
"beautifulsoup4",
"langchain==1.2.15", 
"langchain-core==1.2.29", 
"langchain-openai==1.1.12", 
"openai==2.32.0", 
"pyserini", 
"sentence-transformers==5.4.1", 
"sentencepiece==0.2.1", 
]
name = "class-env"
version = "0.1.0"

[tool.pixi.workspace]
channels = ["conda-forge", "r"]
platforms = ["linux-64", "win-64", "osx-arm64"]

[tool.pixi.tasks]

[tool.pixi.dependencies]
ipykernel = "*"
ipywidgets = "*"
jupyterlab = "*"
scikit-learn = "*"
seaborn = "*"
seqeval = { version = "==1.2.2", build = "pyhd3deb0d_0" }
tokenizers = "*"
python = "3.11.*"
nltk = ">=3.10.3,<4"
jupyterhub = "5.2.1.*"
